# Generated by Django 5.1.1 on 2026-02-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0004_complete_migration"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="registration",
            new_name="registratio_partici_24192a_idx",
            old_name="registratio_participant_",
        ),
    ]
