# Generated by Django 5.1.1 on 2026-02-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_complete_migration"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventfeedback",
            new_name="reports_eve_partici_d7fe02_idx",
            old_name="reports_eve_participant_",
        ),
    ]
