# Generated by Django 5.1.1 on 2026-02-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="poster_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_posters/"),
        ),
    ]
