# Generated by Django 5.1.1 on 2026-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_update_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("participant", "Participant"),
                    ("organizer", "Event Organizer"),
                ],
                default="participant",
                max_length=12,
            ),
        ),
    ]
